### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by jamesdixon** [jimmay5469/ember-computed-validations#1]
@jimmay5469 just wanted to stay great job on this library! I really like the approach. I'm working on integrating it into my application and creating some of my own computed validation macros along the way. Maybe once I've bundled them up, it might make a good addition to the library.

Cheers,
James

**Comment by jimmay5469** [comment]
Thanks a lot!  Glad you're getting some use out of it!  Sounds like that might be a cool direction for the library to go so feel free to open a PR if you pull them together!
