### ISSUE TITLE
Grabbing messages from i18n

### ISSUE THREAD

**Issue by jamesdixon** [jimmay5469/ember-computed-validations#2]
Hey @jimmay5469 - question for you:

I'm attempting to externalize all of my text using `ember-i18n` and normally after injecting the service into my component, I'd call something like `this.get('i18n').t('forms.misc.required')`. Unfortunately, when I try to do this within the `computedValidations` object, `this` is undefined. I'm relatively new to Ember, but it seems that `this` can only be referenced in a function. 

Any thoughts on doing this? Love the addon, but having all that text buried in the component is getting nasty!

Thanks!
James

**Comment by jimmay5469** [comment]
It probably wouldn't be too hard for me to allow specifying either a string or a function returning a string for the error message.  This would also help with a scenario I ran into: dynamic error messages (ex - `This field only allows 100 characters, you are using x`).  I imagine the api would look something like this:

```
  computedValidations: {
    email: {
      emailExists: function() {
        return this.get('i18n').t('forms.misc.required');
      }
    }
  }
```

or this for my scenario:

```
  computedValidations: {
    email: {
      emailNotTooLong: function() {
        return `This field only allows 100 characters, you are using ${this.get('email').length}`;
      }
    }
  }
```

I'd have to play around a little with it and see how it works out but would the above API suffice for your scenario?

I'll let you know if I think of any different APIs that might be nicer and also feel free to share if you have any ideas that you would like better.

**Comment by jamesdixon** [comment]
I think that's a great solution and can't think of anything better off the top of my head. Let me know if there's anything I can do. Thanks!

**Comment by jimmay5469** [comment]
@jamesdixon, I actually got a little bit of time to work on this tonight.  I've already released [v0.0.3](https://github.com/jimmay5469/ember-computed-validations/releases/tag/v0.0.3) with the feature addition.  Let me know how it works out!

**Comment by jamesdixon** [comment]
@jimmay5469 awesome! appreciate the quick turnaround. I'll give it a try now and report back

**Comment by jimmay5469** [comment]
No problem!  It was a pretty easy one!

**Comment by jamesdixon** [comment]
Works like a charm!

**Comment by jimmay5469** [comment]
:+1:
